### PR TITLE
Fix argv0 mutation

### PR DESCRIPTION
**Pull request by ferrouswheel**
But first fix the actual build.

### CODE REVIEW

**Comment by ferrouswheel** [comment]
Ready for merge.

**Comment by Ophien** [comment]
This PR broke the 

```
int GuileSessionManager::startSession(int &rOutputToken, int *pInGhostID, vector<string> *modules, vector<string> *agents) 
```

which consequently broke the session management and processes creation through the 

```
static void callSession(const string &rSessionProgram, const string &rReadPipe, const string &rWritePipe, const vector<string> *modules, const vector<string> *agents)
```

The path stored inside of 

```
 abs_exe_path
```
Needs to be absolute, otherwise the guile session manager will not be able to call for guileSession programs considering the way the callSession method was implemented. This argv[0] mutation is not actually and 'argv' mutation, it is the absolute path of the guile session program and it was necessary for the system(...) call to work from within another process.

```
static void callSession(const string &rSessionProgram, 
                        const string &rReadPipe, 
                        const string &rWritePipe, 
                        const vector<string> *modules, 
                        const vector<string> *agents)
{

    string call = rSessionProgram + " " + rReadPipe + " " + rWritePipe + " ";

    if (modules != nullptr) {
        for (unsigned int module = 0; module < modules->size(); module++) {
            call += (*modules)[module] + " ";
        }
    }

    if (agents != nullptr) {
        for (unsigned int agent = 0; agent < agents->size(); agent++) {
            call += (*agents)[agent] + " ";
        }
    }
    system(call.c_str());
}
```

This was done as a fast workaround to avoid dealing with system calls and forks. 

http://www.cplusplus.com/reference/cstdlib/system/

**Comment by ferrouswheel** [comment]
Ah, so the static function actually needs to return the path and we're still relying on argv[0] pointer somewhere else.

It was still broken before my change. I just didn't write this code so erroneously assumed it would return the path like any sensible implementation would.

**Comment by ferrouswheel** [comment]
Hmm, that wasn't it and I don't quite understand what the issue is...

The code absolutely was changing the argv0 pointer (before this PR), because I could see the result of the mutation in `ps` and `/proc`.

**Comment by Ophien** [comment]
Sorry, I see now why the argv[0] from the main program was being mutated... just lack of attention.

**Pull request merged**
